const investmentPortfolio = [
    {
        stockTicker: 'u',
        currency: 'usd',
        buyDate: '12.11.2021',
        buyPrice: 187.2,
        volume: 1,
        usdRubRateBuyDate: 72.97,
        benchMark: 'fxit.me',
        benchMarkStartPrice: 12082,
    },
    {
        stockTicker: 'rblx',
        currency: 'usd',
        buyDate: '03.11.2021',
        buyPrice: 78.72,
        volume: 2,
        usdRubRateBuyDate: 73.09,
        benchMark: 'fxit.me',
        benchMarkStartPrice: 11696,
    },
    {
        stockTicker: 'nvda',
        currency: 'usd',
        buyDate: '10.07.2020',
        buyPrice: 104.35,
        volume: 4,
        usdRubRateBuyDate: 73,
        benchMark: 'fxit.me',
        benchMarkStartPrice: 7618,
    },
    {
        stockTicker: 'fb',
        currency: 'usd',
        buyDate: '25.03.2020',
        buyPrice: 160.14,
        volume: 1,
        usdRubRateBuyDate: 80.32,
        benchMark: 'fxit.me',
        benchMarkStartPrice: 5857,
    },
    {
        stockTicker: 'mtch',
        currency: 'usd',
        buyDate: '25.03.2020',
        buyPrice: 63.99,
        volume: 1,
        usdRubRateBuyDate: 66.57,
        benchMark: 'fxit.me',
        benchMarkStartPrice: 5857,
    },
    {
        stockTicker: 'aapl',
        currency: 'usd',
        buyDate: '25.02.2020',
        buyPrice: 73.22,
        volume: 4,
        usdRubRateBuyDate: 67,
        benchMark: 'fxit.me',
        benchMarkStartPrice: 5993,
    },
    {
        stockTicker: 'tcsg.me',
        currency: 'rub',
        buyDate: '10.01.2020',
        buyPrice: 1370,
        lastPrice: 6848,
        volume: 2,
        usdRubRateBuyDate: 66.57,
        benchMark: 'fxit.me',
        benchMarkStartPrice: 5993,
    },
    {
        stockTicker: 'yndx.me',
        currency: 'rub',
        buyDate: '10.01.2020',
        buyPrice: 2732,
        lastPrice: 5612,
        volume: 1,
        usdRubRateBuyDate: 66.57,
        benchMark: 'fxit.me',
        benchMarkStartPrice: 5675,
    },
    {
        stockTicker: 'fxit.me',
        currency: 'rub',
        buyDate: '10.01.2020',
        buyPrice: 5675,
        lastPrice: 12382,
        volume: 1,
        usdRubRateBuyDate: 66.57,
        benchMark: 'fxit.me',
        benchMarkStartPrice: 5675,
    }
]